/* ============================================================
   HMG ACADEMY CLASS DECK — License & Subscription Engine
   ------------------------------------------------------------
   For the HMG-owned ClassDeck, this is a LIFETIME license stub —
   the platform never expires (owner account is always unlocked).
   For generated client decks, js/license.js is regenerated by the
   ClassDeck Generator with the client's subscription/lifetime model.
   ============================================================ */
"use strict";

window.CD_LICENSE = {
  model: "lifetime",        // lifetime = never locks
  plan: "HMG ACADEMY — Platform Owner (Lifetime)",
  cycle: "",
  price: "",
  started_on: "",
  expires_on: null,         // null = never expires
  grace_days: 0,
  renew_url: "",
  contact: "Adewale Samson Adeagbo — 08100866322 / 08094481488",
  lock_msg: ""
};

console.log("[ClassDeck] HMG lifetime license active — owner account never expires.");