#!/usr/bin/env python3
"""
build_seo.py — generate a site-correct robots.txt and sitemap.xml
=================================================================

THE BUG THIS FIXES (found by probing the live site, not by reading code)

    $ curl https://adewaleclassroom.vercel.app/sitemap.xml
    <loc>https://tutoringconnect.vercel.app/</loc>
    <loc>https://tutoringconnect.vercel.app/builder.html</loc>

The generated client studio was serving the GENERATOR's sitemap. It pointed
search engines at a different domain entirely, and advertised builder.html,
which returns 404 on a client site. robots.txt was byte-identical between the
two repos for the same reason: the sync procedure copied both files verbatim
and nothing ever regenerated them per-site.

Two further defects in the inherited robots.txt:

  * `Sitemap: sitemap.xml` is a RELATIVE url. The robots.txt specification
    requires an absolute URL; most crawlers ignore a relative one, so the
    sitemap was effectively undiscoverable.
  * It disallowed exactly two private pages (admin-data, safeguarding) while
    roughly 120 other private portal pages were left open to indexing.

This script derives everything from the site's own config.js, so a generated
studio can never again inherit the generator's identity.

USAGE
    python3 tools/build_seo.py                 # current repo
    python3 tools/build_seo.py /path/to/site
"""

import os
import re
import sys
import datetime

# Pages that SHOULD be indexed. Everything else in the studio is private and
# is both disallowed in robots.txt and marked noindex in the page itself.
PUBLIC_PAGES = [
    'index.html', 'about.html', 'apply.html', 'contact.html',
    'exam-register.html', 'public-book.html', 'feature-guide.html',
    'hmg-ecosystem.html', 'hmg-products.html', 'flyer.html',
    'install.html', 'developer.html', 'site-index.html',
]

# Generator-only pages. These must never appear in a CLIENT sitemap.
GENERATOR_ONLY = {'builder.html'}


def read_cfg(root):
    p = os.path.join(root, 'assets', 'js', 'config.js')
    if not os.path.exists(p):
        return {}
    s = open(p, encoding='utf-8').read()
    out = {}
    for k in ('siteUrl', 'name', 'shortName', 'motto', 'schoolName'):
        m = re.search(k + r"\s*:\s*['\"]([^'\"]*)['\"]", s)
        if m:
            out[k] = m.group(1)
    return out


def main():
    root = os.path.abspath(sys.argv[1] if len(sys.argv) > 1
                           else os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
    cfg = read_cfg(root)
    base = (cfg.get('siteUrl') or '').rstrip('/')
    if not base:
        base = 'https://example.com'
    name = cfg.get('name') or cfg.get('schoolName') or 'Tutoring studio'

    is_generator = os.path.exists(os.path.join(root, 'builder.html'))

    present = {f for f in os.listdir(root) if f.endswith('.html')}
    public = [f for f in PUBLIC_PAGES if f in present]
    if is_generator and 'builder.html' in present:
        public.append('builder.html')          # the generator DOES want this indexed
    private = sorted(present - set(public) - GENERATOR_ONLY)

    today = datetime.date.today().isoformat()

    # ---------------- sitemap.xml ----------------
    urls = []
    for f in public:
        loc = base + '/' + ('' if f == 'index.html' else f)
        pri = '1.0' if f == 'index.html' else '0.8'
        urls.append(
            '  <url>\n'
            '    <loc>%s</loc>\n'
            '    <lastmod>%s</lastmod>\n'
            '    <changefreq>weekly</changefreq>\n'
            '    <priority>%s</priority>\n'
            '  </url>' % (loc, today, pri))

    sitemap = ('<?xml version="1.0" encoding="UTF-8"?>\n'
               '<!-- %s — generated by tools/build_seo.py on %s.\n'
               '     Derived from this site\'s own config.js siteUrl, so a generated\n'
               '     studio can never inherit the generator\'s domain. -->\n'
               '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
               '%s\n</urlset>\n' % (name, today, '\n'.join(urls)))

    # ---------------- robots.txt ----------------
    lines = [
        '# %s' % name,
        '# Generated by tools/build_seo.py on %s' % today,
        '#',
        '# Public pages are listed explicitly. Every other page in this studio is',
        '# a private portal screen and is disallowed below AND carries a noindex',
        '# meta tag, because robots.txt alone is a request, not access control.',
        '',
        'User-agent: *',
    ]
    for f in public:
        lines.append('Allow: /' + ('' if f == 'index.html' else f))
    lines.append('')
    for f in private:
        lines.append('Disallow: /' + f)
    lines += [
        '',
        '# Named crawlers, so the studio is findable on both major engines.',
        'User-agent: Googlebot',
        'Allow: /',
        '',
        'User-agent: Bingbot',
        'Allow: /',
        '',
        '# Absolute URL — the specification requires it; a relative path is ignored.',
        'Sitemap: %s/sitemap.xml' % base,
        '',
    ]

    open(os.path.join(root, 'sitemap.xml'), 'w', encoding='utf-8').write(sitemap)
    open(os.path.join(root, 'robots.txt'), 'w', encoding='utf-8').write('\n'.join(lines))

    # ---------------- noindex on every private page ----------------
    TAG = '<meta name="robots" content="noindex,nofollow">'
    touched = 0
    for f in private:
        p = os.path.join(root, f)
        s = open(p, encoding='utf-8').read()
        s2 = re.sub(r'\s*<meta name="robots"[^>]*>', '', s)
        if '</title>' in s2:
            s2 = s2.replace('</title>', '</title>\n' + TAG, 1)
        elif '</head>' in s2:
            s2 = s2.replace('</head>', TAG + '\n</head>', 1)
        if s2 != s:
            open(p, 'w', encoding='utf-8').write(s2)
            touched += 1

    # Public pages must NOT carry noindex — strip any that leaked in.
    cleaned = 0
    for f in public:
        p = os.path.join(root, f)
        s = open(p, encoding='utf-8').read()
        s2 = re.sub(r'\s*<meta name="robots" content="noindex[^>]*>', '', s)
        if s2 != s:
            open(p, 'w', encoding='utf-8').write(s2)
            cleaned += 1

    print('   SEO for %-22s base=%s' % (name, base))
    print('   public=%d  private=%d  noindex added=%d  noindex cleaned=%d'
          % (len(public), len(private), touched, cleaned))
    return 0


if __name__ == '__main__':
    sys.exit(main())
